#!/bin/bash

# -----------------------------------------------
# This function calculate and print out 
# the sum, difference, product and division of 
# two numbers(given as parameters when the function is called).

# Usage example: calculation 6 2
# -----------------------------------------------

Calc ()
{
# 1) print out the given numbers
echo "You gave two integers: $1 and $2"

# 2) calculate and store the operations
                Sum=$(($1+$2))
                Diff=$(($1-$2))
                Prod=$(($1*$2))
                if [ $2 -eq 0 ]
                then
                        Div="Undefined(division by zero)"
                else
                        Div=$(($1/$2))
                fi

                # 3) print out the result
                echo "
The calculation result is shown below:
Sum         $Sum
Difference  $Diff
Product     $Prod
Division    $Div"
}
